### ISSUE TITLE
Minimize the uneeded configuration properties

### ISSUE THREAD

**Issue by ProbablePrime** [voxelbonecloud/pterodactyl-resonite#1]
I don't know where your config.json is as I'm not familiar with Pterodactly(i cant even spell it), however. 

As described in: https://github.com/Resonite-Community-Projects/resonite-pterodactyl/issues/9

The final config.json should have as many null, "", {}, []'s removed as possible to avoid confusion.

**Comment by bredo228** [comment]
We don't provide a Config.json with this egg - it's up to whoever's setting up the headless to provide one.
